# Configuration file for pre-commit (https://pre-commit.com/).
# Please run `pre-commit run --all-files` when adding or changing entries.

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.9.10'
    hooks:
    - id: ruff
      args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix]
    - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ".*\\.py$"